name: GetScreen Windows (6H)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Downloading & Setting Up
        run: |
         echo "EMAIL_SECRET=toxoj82946@felibg.com" > secrets.txt
         Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/spcwkc73x8htjwd012kcm/down.bat?rlkey=12ghp98nlyi3oh8u5nvbazdf0&dl=1" -OutFile "down.bat"
         cmd /c down.bat

      - name: Time Counter
        run: python time.py
